### ISSUE TITLE
Getting node-gyp error while adding provider

### ISSUE THREAD

**Issue by ShubhamChndrvnshi** [ArkaneNetwork/web3-arkane-provider#39]
Here is the error
`
warning Error running install script for optional dependency: "/Users/shubham/Desktop/Code/Sokos/frontend/node_modules/node-hid: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /Users/shubham/Desktop/Code/Sokos/frontend/node_modules/node-hid
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.18.1 runtime=node arch=arm64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.1 | darwin | arm64
gyp info find Python using Python version 3.9.10 found at \"/opt/homebrew/opt/python@3.9/bin/python3.9\"
gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/shubham/Desktop/Code/Sokos/frontend/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/shubham/Library/Caches/node-gyp/14.18.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/shubham/Library/Caches/node-gyp/14.18.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/shubham/Library/Caches/node-gyp/14.18.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/shubham/Desktop/Code/Sokos/frontend/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/hidapi/hidapi/mac/hid.o
  LIBTOOL-STATIC Release/hidapi.a
env: python: No such file or directory
make: *** [Release/hidapi.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command \"/Users/shubham/.nvm/versions/node/v14.18.1/bin/node\" \"/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/shubham/Desktop/Code/Sokos/frontend/node_modules/node-hid
[-/11] ⠈ waiting...
[6/11] ⠈ secp256k1
[-/11] ⠈ waiting...
[8/11] ⠈ usb
warning Error running install script for optional dependency: "/Users/shubham/Desktop/Code/Sokos/frontend/node_modules/usb: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments: 
Directory: /Users/shubham/Desktop/Code/Sokos/frontend/node_modules/usb
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.1 | darwin | arm64
gyp info find Python using Python version 3.9.10 found at \"/opt/homebrew/opt/python@3.9/bin/python3.9\"
gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/shubham/Desktop/Code/Sokos/frontend/node_modules/usb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/shubham/Library/Caches/node-gyp/14.18.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/shubham/Library/Caches/node-gyp/14.18.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/shubham/Library/Caches/node-gyp/14.18.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/shubham/Desktop/Code/Sokos/frontend/node_modules/usb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
../libusb/libusb/io.c:2300:30: warning: comparison of integers of different signs: 'int' and 'nfds_t' (aka 'unsigned int') [-Wsign-compare]
                for (i = internal_nfds ; i < nfds ; ++i) {
                                         ~ ^ ~~~~
1 warning generated.
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/darwin_usb.o
  LIBTOOL-STATIC Release/usb.a
env: python: No such file or directory
make: *** [Release/usb.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command \"/Users/shubham/.nvm/versions/node/v14.18.1/bin/node\" \"/Users/shubham/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/shubham/Desktop/Code/Sokos/frontend/node_modules/usb
`

shubham@shubhams-MacBook-Pro frontend % node -v
v14.18.1
shubham@shubhams-MacBook-Pro frontend % yarn --version
1.22.17
Chip:
M1 Pro

**Comment by tomtomdu73** [comment]
Same here

**Comment by nico-ptrs** [comment]
Obsolete — `node-hid`/`usb`/`secp256k1` were pulled in via `@0x/subproviders`, which is no longer a dependency. Closing.
